FROM openjdk:11.0.6-jre-buster
ADD https://github.com/mpadmaraj/optaplanner-quickstarts/blob/stable/spring-boot-school-timetabling/jar/optaplanner-spring-boot-school-timetabling-quickstart-1.0-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
