FROM openjdk:11.0.6-jre-buster
ADD https://github.com/mpadmaraj/optaplanner-quickstarts/blob/stable/spring-boot-school-timetabling/jar/spring-boot-school-timetabling-1.0-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.jar"]
